name: .NET Core  

on:  
  push:  
    branches: [ master ]  
  pull_request:  
    branches: [ master ]  

jobs:  
  build: 
    runs-on: ubuntu-latest  
    steps:  
    - uses: actions/checkout@v2  
    - name: Setup .NET Core  
      uses: actions/setup-dotnet@v1  
      with:  
        dotnet-version: 5.0.x  
    - name: Install dependencies  
      run: dotnet restore src/EasyCors
    - name: Build  
      run: dotnet build --configuration Release --no-restore  src/EasyCors
    - name: Test  
      run: dotnet test --no-restore --verbosity normal  src/AWSSecretManager.Configuration.Extension/AWSSecretManager.Configuration.Extension
    - name: Publish  
      uses: brandedoutcast/publish-nuget@v2.5.2  
      with:   
        PROJECT_FILE_PATH: src/EasyCors/EasyCors.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}} 